### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim-Website#202] opened 2016-11-30 16:40 UTC
> Hi Glenn, 
> 
> Whilst researching Backbone.js resources to cite on our website, I found one of your links isn’t working.
> 
> It's this link that seems to be broken: http://documentcloud.github.com/backbone/, here on this page of your site http://docs.slimframework.com/routing/delete/, using this text "Backbone.js".
> 
> Please check out our resource http://wiht.link/backbonejs-intro as it may prove a useful replacement.
> 
> Best,
> Chris

Link Broken: http://documentcloud.github.io/backbone/

Context:
```
<p>If you are using <a href="http://documentcloud.github.com/backbone/">Backbone.js</a> or a command-line HTTP client, you may also override the HTTP method by
using the <strong>X-HTTP-Method-Override</strong> header.</p>
```

**Comment by svpernova09** [comment] 2018-02-10 17:51
Since the issue is on the `slimphp/Slim-Documentation-2.x` repo (and I just poked the bear to say the PR looks good) we can close this since this site doesn't mention Backbone.

**Closed as completed** 2018-02-10 21:49 UTC
