### ISSUE TITLE
Web Servers Apache configuration

### ISSUE THREAD

**Issue by n0x073** [slimphp/Slim-Website#582] opened 2021-07-28 10:44 UTC
There is an easier way to configure apache instead use rewrite:
```
DirectoryIndex /index.php
FallbackResource /index.php
```
DirectoryIndex can be normally omitted if the file is called index.php

The advantage over [mod_rewrite](https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html) is [mod_dir](https://httpd.apache.org/docs/2.4/mod/mod_dir.html) is default builtin and enabled in apache.

**Comment by odan** [comment] 2021-07-28 11:28
I have tried it and I get an `Internal Server Error`. 
How do you configure it when you have placed the front controller in `public/index.php`?
How do you handle routing when running the Slim app in a sub-directory of the DocumentRoot?

**Comment by n0x073** [comment] 2021-07-28 12:15
> I have tried it and I get an Internal Server Error.

something in errorlogs?

> How do you configure it when you have placed the front controller in public/index.php?

if apache DocumentRoot is public
public/.htaccess
```
DirectoryIndex /index.php
FallbackResource /index.php
```

> How do you handle routing when running the Slim app in a sub-directory of the DocumentRoot?

public/**someotherdirectory**/index.php
```
[...]
$app->setBasePath('/someotherdirectory');
[...]
```
public/**someotherdirectory**/.htaccess
```
DirectoryIndex /someotherdirectory/index.php
FallbackResource /someotherdirectory/index.php
```

**Comment by odan** [comment] 2021-07-28 13:19
A simple `GET / ` request seems to work. But as soon I try to return a HTTP redirect (302) to another URL like `docs/v1` it's not working anymore.

`Internal server error`

Apache logfile:

```
AH00125: Request exceeded the limit of 10 subrequest nesting levels due to probable configuration error. 
Use 'LimitInternalRecursion' to increase the limit if necessary. 
Use 'LogLevel debug' to get a backtrace.
```

**Comment by n0x073** [comment] 2021-07-28 13:34
Cant reproduce your problems, tried the redirect router component and the redirect within a controller without a problem
```php
<?php
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\Factory\AppFactory;

require __DIR__ . '/../vendor/autoload.php';

$app = AppFactory::create();

$app->redirect('/testredirect/', '/test/', 302);
$app->get('/', function (Request $request, Response $response, $args) {
    $response->getBody()->write("Hello world!");
	

    return $response->withHeader('Location', '/test/')->withStatus(302);
	
    return $response;
});


$app->get('/test/', function (Request $request, Response $response, $args) {
    $response->getBody()->write("Hello test!");
    return $response;
});

$app->run();
```

**Comment by odan** [comment] 2021-07-28 14:00
I guess the problem is not the redirect. It's every route with more than one path in the route, e.g. `test/test2` or `api/v1`

**Comment by n0x073** [comment] 2021-07-28 14:39
```php
$app->get('/test1/test2/test3/', function (Request $request, Response $response) {
        $response->getBody()->write('Hello test 123!');
        return $response;
    })->setName('testtarget');

    $app->redirect('/test1/route/redirect/', $app->getRouteCollector()->getRouteParser()->urlFor('testtarget'), 302);
    $app->get('/test1/test2/redirect/', function (Request $request, Response $response) use($app) {
        $routeParser = $app->getRouteCollector()->getRouteParser();
        return $response->withHeader('Location', $routeParser->urlFor('testtarget'))->withStatus(302);
    });
```
Works (with and without subfolder)
![image](https://user-images.githubusercontent.com/72650981/127341352-8839ed0a-3829-4a76-9ba8-6b18b8729dc1.png)

**Comment by odan** [comment] 2024-06-30 15:05
Closed as solved.

**Closed as completed by odan** 2024-06-30 15:05 UTC
